### ISSUE TITLE
Unable to build the package

### ISSUE THREAD

**Issue by pallyra1** [ros-geographic-info/open_street_map#12]
Hello
I am new to ROS
Upon using "catkin build", I am getting this,

-- Could not find the required component 'geodesy'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "geodesy" with any
  of the following names:

    geodesyConfig.cmake
    geodesy-config.cmake

  Add the installation prefix of "geodesy" to CMAKE_PREFIX_PATH or set
  "geodesy_DIR" to a directory containing one of the above files.  If
  "geodesy" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  open_street_map/osm_cartography/CMakeLists.txt:17 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pallav/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/pallav/catkin_ws/build/CMakeFiles/CMakeError.log".

How to find geodesy-config file?

**Comment by bmagyar** [comment]
This is an issue tracker for the software where we track bugs. 

The right forum for this type of questions is [ros answers](https://answers.ros.org/questions/). You can search a solution to your problem or raise a new question if you can't find it.
