### ISSUE TITLE
does not work with <geographic_info-0.4.0>

### ISSUE THREAD

**Issue by trigal** [ros-geographic-info/open_street_map#3]
Hi, I would like to report an issue with the last release of geographic_info (0.4.0). The problem is related to the geodesy_gen_uuid , removed since deprecated (https://github.com/ros-geographic-info/geographic_info/issues/4). 

Following the procedure stated in [doc/geodesy.gen_uuid.rst](https://github.com/ros-geographic-info/geographic_info/blob/e7d48ea6212d6900a3d73b840e4fba01a34e7696/geodesy/geodesy.gen_uuid.rst) everything is ok now. 

There are few changes in these files:

osm_cartography/src/osm_cartography/xml_map.py
route_network/scripts/route_network
route_network/tests/test_planner.py

I'm going to create a fork for the project and then a pull request, it's ok for you?

**Comment by Fenix0817** [comment]
Hi Jack, I have a problem with osm_cartography.

When I use the example in the launch file (viz_osm.launch), give me the next error:

Traceback (most recent call last):
  File "/home/andres/ros_ws/open_street_map/osm_cartography/scripts/osm_server", line 51, in <module>
    from osm_cartography import xml_map
ImportError: No module named osm_cartography
Traceback (most recent call last):
  File "/home/andres/ros_ws/open_street_map/osm_cartography/scripts/viz_osm", line 65, in <module>
    import osm_cartography.cfg.VizOSMConfig as Config
ImportError: No module named osm_cartography.cfg.VizOSMConfig

I am work just now with ROS indigo. Please, Can you help me?

**Comment by jack-oquin** [comment]
Did you install osm_cartography from source or from binaries?

**Comment by jack-oquin** [comment]
Please post what command you ran to get that crash. Was it this?
```
roslaunch osm_cartography viz_osm.launch
```

That is not crashing for me right now.

**Comment by Fenix0817** [comment]
Hi Jack,

Yes, the command was that "roslaunch osm_cartography viz_osm.launch".



2015-10-07 22:52 GMT+02:00 jack-oquin <notifications@github.com>:

> Please post what command you ran to get that crash. Was it this?
>
> roslaunch osm_cartography viz_osm.launch
>
> That is not crashing for me right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros-geographic-info/open_street_map/issues/3#issuecomment-146324581>
> .
>



-- 
*Andrés *

**Comment by jack-oquin** [comment]
@Fenix0817: I suspect there is something wrong with your workspace or your ROS environment setup.
