### ISSUE TITLE
other maps not shown on RVIZ (with default launcher)

### ISSUE THREAD

**Issue by trigal** [ros-geographic-info/open_street_map#5]
Hi, I'm opening the issue following [this post](https://groups.google.com/forum/#!topic/utexas-art-ros-pkg-users/Vm3twjcMqYA) on the utexas-art-ros-pkg-users group.

I would report that if you try to open the launch file inside the osm_cartography folder, there is a static transform:  
`<node pkg="tf" type="static_transform_publisher" name="local_map_tf" args="622150 3362350 0 0 0 0 1 map local_map 100" />`

this is the transform to the UTM reference frame for the downloaded openstreetmap. 
If you try do download your own map, you need to create a new transform with the coordinates of your area, in order to see the map on RVIZ.

I think this should be included in the readme of the project :-)

PS: here is a useful link for the lat/lon to UTM conversion http://www.rcn.montana.edu/resources/converter.aspx

**Comment by jack-oquin** [comment]
Closed as included in release 0.2.3 to Indigo. 

Documentation added [to the wiki](http://wiki.ros.org/osm_cartography#viz_osm_Launch_File). Please feel free to make or suggest improvements.
