### ISSUE TITLE
How  to use GPS data with Open Street Map

### ISSUE THREAD

**Issue by jjkllll** [ros-geographic-info/open_street_map#7]
I am new to ROS. I am getting GPS data published. I want to use it to plot a map and with start and end coordinates i want to know about the distances and directions. I don't know how to use the package to prove it the GPS data and also how to get the desired route. Please help me.

**Comment by jack-oquin** [comment]
The ``osm_cartography`` package handles map data from [Open Street Map](http://www.openstreetmap.org). 

Is the map you wish to plot there? If so, you can use these packages to plot a map and find a route through it.

**Comment by pallyra1** [comment]
I want to visualise the map from OpenStreetMaps on Rviz. For that I have downloaded the .osm file. The file's location is this.
file:///home/pallav/Downloads/map%20(1).osm
How do I use this file for visualisation. I am unable to use viz_osm 

Please help!

**Comment by jack-oquin** [comment]
Github issues are for bugs and enhancements in the code.

Please go to http://answers.ros.org for help with ROS and its packages.
